name: PHP CS Fixer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para push funcionar corretamente

      - name: Instalar PHP e dependências
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: php-cs-fixer
          coverage: none

      - name: Rodar PHP-CS-Fixer (corrigir arquivos)
        run: php-cs-fixer fix

      - name: Commit e push das correções (se houver)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          # Se houver mudanças, commit e push
          git diff --cached --quiet || (git commit -m "Corrige formatação automática pelo PHP CS Fixer" && git push)
