name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Cache de dependências
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist

      - name: Verificação de segurança
        run: composer audit || true

      - name: Rodar testes
        run: php artisan test

      - name: Lint (Laravel Pint)
        run: ./vendor/bin/pint --test
